/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.arondight.utils;

import com.google.gson.Gson;

import java.util.*;

@SuppressWarnings("rawtypes")
public class Reader {
    static final String DEFAULT_URL = "https://raw.githubusercontent.com/nats-io/jsm.go/main/schema_source/jetstream/api/v1/definitions.json";

    String refTarget;

    public Reader(String refTarget) {
        this.refTarget = refTarget;
    }

    public void read() throws Exception {
        read(DEFAULT_URL);
    }

    public void read(String url) throws Exception {
        System.out.println("Reading: " + url + "\nTarget: " + refTarget + "\n");

        String json = FileUtils.readUrl(url);

        Gson gson = new Gson();
        Map map = gson.fromJson(json, Map.class);

        Map<String, Map> objects = getObjects((Map)map.get("definitions"));

        List<String> results = new ArrayList<>();
        for (String object : objects.keySet()) {
            processObject(object, objects.get(object), results);
        }

        Collections.sort(results);
        results.forEach(System.out::println);
    }

    private void processObject(String object, Map map, List<String> results) {
        for (Object propKey : map.keySet()) {
            Map props = (Map)map.get(propKey);
            String result = checkRef(object, propKey, props, false);
            if (result == null) {
                Map items = (Map)props.get("items");
                if (items != null) {
                    result = checkRef(object, propKey, items, true);
                }
            }
            if (result != null) {
                results.add(result);
            }
        }
    }

    private String checkRef(String object, Object propKey, Map props, boolean array) {
        String ref = (String)props.get("$ref");
        if (refTarget.equals(ref)) {
            return "- `" + object + "." + propKey + (array ? "` _array_": "`");
        }
        return null;
    }

    private Map<String, Map> getObjects(Map definitions) {
        Map<String, Map> objects = new HashMap<>();

        for (Object oKey : definitions.keySet()) {
            Map def = (Map)definitions.get(oKey);
            String type = (String)def.get("type");
            if ("object".equals(type)) {
                String key = (String)oKey;
                Map props = (Map)((Map)definitions.get(oKey)).get("properties");
                if (props != null) {
                    objects.put(key, props);
                }
            }
        }
        return objects;
    }
}
