/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.arondight;

import com.google.gson.Gson;
import io.arondight.utils.FileUtils;

import java.io.IOException;
import java.util.*;

@SuppressWarnings("rawtypes")
public class NatsJsDefReader {
    public static final String UINT_64 = "#/definitions/golang_uint64";
    static final String URL_TEMPLATE = "https://raw.githubusercontent.com/nats-io/jsm.go/:branch/schema_source/jetstream/api/v1/definitions.json";

    public static void main(String[] args) throws IOException {
        read(UINT_64, "main");
    }

    public static void read(String refTarget, String branch) throws IOException {
        String url = URL_TEMPLATE.replace(":branch", branch);
        String json = FileUtils.readUrl(url);

        Gson gson = new Gson();
        Map map = gson.fromJson(json, Map.class);

        Map<String, Map> objects = getObjects((Map)map.get("definitions"));

        List<String> results = new ArrayList<>();
        for (String object : objects.keySet()) {
            processObject(refTarget, object, objects.get(object), results);
        }

        Collections.sort(results);
        results.forEach(System.out::println);
    }

    private static void processObject(String refTarget, String object, Map map, List<String> results) {
        for (Object propKey : map.keySet()) {
            Map props = (Map)map.get(propKey);
            String result = checkRef(refTarget, object, propKey, props, false);
            if (result == null) {
                Map items = (Map)props.get("items");
                if (items != null) {
                    result = checkRef(refTarget, object, propKey, items, true);
                }
            }
            if (result != null) {
                results.add(result);
            }
        }
    }

    private static String checkRef(String refTarget, String object, Object propKey, Map props, boolean array) {
        String ref = (String)props.get("$ref");
        if (refTarget.equals(ref)) {
            return "- `" + object + "." + propKey + (array ? "` _array_": "`");
        }
        return null;
    }

    private static Map<String, Map> getObjects(Map definitions) {
        Map<String, Map> objects = new HashMap<>();

        for (Object oKey : definitions.keySet()) {
            Map def = (Map)definitions.get(oKey);
            String type = (String)def.get("type");
            if ("object".equals(type)) {
                String key = (String)oKey;
                Map props = (Map)((Map)definitions.get(oKey)).get("properties");
                if (props != null) {
                    objects.put(key, props);
                }
            }
        }
        return objects;
    }
}
